# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class TgctlGo < Formula
  desc "Go port of Python tgctl: single static `tg` binary for Telegram"
  homepage "https://github.com/b1rd33/tgctl-go"
  version "0.7.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/b1rd33/tgctl-go/releases/download/v0.7.0/tgctl-go_0.7.0_darwin_x86_64.tar.gz"
      sha256 "cf95727cc78e56ed0a0fda24c1350e2263001c65a8c21f98c0367e234bf39b5b"

      define_method(:install) do
        bin.install "tg"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/b1rd33/tgctl-go/releases/download/v0.7.0/tgctl-go_0.7.0_darwin_arm64.tar.gz"
      sha256 "77808229d849dc8c9645b81cd84abdc68d05230c1b41b8325c00ebf96499925d"

      define_method(:install) do
        bin.install "tg"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/b1rd33/tgctl-go/releases/download/v0.7.0/tgctl-go_0.7.0_linux_x86_64.tar.gz"
      sha256 "25473b9121e3331fd13f9e874857ecab91e1e0a9eebf885d366200e5eea8197f"
      define_method(:install) do
        bin.install "tg"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/b1rd33/tgctl-go/releases/download/v0.7.0/tgctl-go_0.7.0_linux_arm64.tar.gz"
      sha256 "903cfee89863b81775abb981c4ef8c57807d2dcef56961a1d537240a58070107"
      define_method(:install) do
        bin.install "tg"
      end
    end
  end

  test do
    assert_match(/\Av?\d+\.\d+\.\d+/, shell_output("#{bin}/tg --version"))
  end
end
